<?php

/**
 * @file
 * Contains reseau_mod_up_formation.module.
 */

use Drupal\views\ViewExecutable;

/**
 * Implements hook_entity_type_alter().
 *
 * @param array $entity_types
 */
function reseau_mod_up_formation_entity_type_alter(array &$entity_types)
{
  // Add validation constraint to the node entity
  if (isset($entity_types['node'])) {
    $entity_types['node']->addConstraint('AtLeastOneFormationIdentifier');

    // dsm($entity_types['node']);
  }
}


function reseau_mod_up_formation_page_attachments_alter(array &$attachments)
{

  /*ajoute css admin*/
  $admin_theme = \Drupal::config('system.theme')->get('admin');
  $admin_theme_name = \Drupal::service('theme_handler')->getName($admin_theme);
  if ($admin_theme_name == 'Seven') {
    $attachments['#attached']['library'][] = 'reseau_mod_up_formation/extra.admin';
  }
}

/**
 * Implements hook_theme().
 */
function reseau_mod_up_formation_theme()
{

  $theme['node__contact__handicap'] = [
    'base hook' => 'node',
  ];


  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */

function reseau_mod_up_formation_theme_suggestions_node(array $variables)
{
  $node = $variables['elements']['#node'];
  $suggestions = [];
  if ((doesBundleHaveField($node->getEntityTypeId(), $node->bundle(), 'field_ctc_ref_handicap')) && (!empty($node->get('field_ctc_ref_handicap')->getValue()))) {
    $contactHandicap = $node->get('field_ctc_ref_handicap')->getValue();
    if ($contactHandicap[0]['value'] == TRUE) {
      $suggestions[] = 'node__contact__handicap';
    }
  }


  return $suggestions;
}


/** Ms **/
function reseau_mod_up_formation_views_pre_build(ViewExecutable $view)
{


  if ($view->id() == 'sliders') {
    if ($view->current_display == 'block_5') {
      $current_path = \Drupal::service('path.current')->getPath();
      $result = \Drupal::service('path_alias.manager')->getAliasByPath($current_path);

      //       $vid = 'public';
      // $terms =\Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree($vid);
      // foreach ($terms as $term) {

      //   $output = Html::getClass($term->name);

      //  $term_data[] = array(
      //   'id' => $term->tid,
      //   'name' => $output
      //  );
      // }
      // dsm($term_data);

      switch (basename($result)) {
        case 'demandeur-demploi':
          $tax_id = '11';
          break;
        case 'jeune-16-29-ans':
          $tax_id = '12';
          break;
        case 'salarie':
          $tax_id = '15';
          break;
        case 'individuel-autre-statut':
          $tax_id = '17';
          break;
        case 'employeur':
          $tax_id = '20';
          break;
        case 'partenaires':
          $tax_id = '13';
          break;

        default:
          $tax_id = 'all';
          break;
      }
      $view->args[0] = $tax_id;
    }
  }
}